### ISSUE TITLE
Add support for "environments"

### ISSUE THREAD

**Issue by quintesse** [fabric8-launcher/launcher-booster-catalog-service#24]
See https://github.com/fabric8-launcher/launcher-planning/issues/81#issuecomment-349300573

The idea is that a booster.yaml file could look like this:

```
githubRepo: https://github.com/some/boosters.git
gitRef: master
environments:
  staging:
    gitRef: v15
  production:
    gitRef: v14
```

Meaning that by default we use the `master` version of the booster repository. But if we ask for the version in "staging" we get `v15` (a specific version still being tested). And if we'd ask for "production" we'd get `v14` (a specific certified version).

This works by simply applying the environment as an "overlay" on top of the existing data.

We should also add an `environment` attribute to the `BoosterCatalogService` so that by default it returns boosters for that specific environment.
